/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { BillCreateNestedManyWithoutNestsInput } from "./BillCreateNestedManyWithoutNestsInput";
import {
  ValidateNested,
  IsOptional,
  IsBoolean,
  IsString,
} from "class-validator";
import { Type } from "class-transformer";
import { PropertyWhereUniqueInput } from "../../property/base/PropertyWhereUniqueInput";
import { RentCreateNestedManyWithoutNestsInput } from "./RentCreateNestedManyWithoutNestsInput";
import { TenantCreateNestedManyWithoutNestsInput } from "./TenantCreateNestedManyWithoutNestsInput";

@InputType()
class NestCreateInput {
  @ApiProperty({
    required: false,
    type: () => BillCreateNestedManyWithoutNestsInput,
  })
  @ValidateNested()
  @Type(() => BillCreateNestedManyWithoutNestsInput)
  @IsOptional()
  @Field(() => BillCreateNestedManyWithoutNestsInput, {
    nullable: true,
  })
  bills?: BillCreateNestedManyWithoutNestsInput;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isOccupied!: boolean;

  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  isUnit!: boolean;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
    type: () => PropertyWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PropertyWhereUniqueInput)
  @Field(() => PropertyWhereUniqueInput)
  propertyId!: PropertyWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RentCreateNestedManyWithoutNestsInput,
  })
  @ValidateNested()
  @Type(() => RentCreateNestedManyWithoutNestsInput)
  @IsOptional()
  @Field(() => RentCreateNestedManyWithoutNestsInput, {
    nullable: true,
  })
  rents?: RentCreateNestedManyWithoutNestsInput;

  @ApiProperty({
    required: false,
    type: () => TenantCreateNestedManyWithoutNestsInput,
  })
  @ValidateNested()
  @Type(() => TenantCreateNestedManyWithoutNestsInput)
  @IsOptional()
  @Field(() => TenantCreateNestedManyWithoutNestsInput, {
    nullable: true,
  })
  tenants?: TenantCreateNestedManyWithoutNestsInput;
}

export { NestCreateInput as NestCreateInput };
