/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Nest, Bill, Rent, Tenant, Property } from "@prisma/client";

export class NestServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.NestFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestFindManyArgs>
  ): Promise<number> {
    return this.prisma.nest.count(args);
  }

  async findMany<T extends Prisma.NestFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestFindManyArgs>
  ): Promise<Nest[]> {
    return this.prisma.nest.findMany(args);
  }
  async findOne<T extends Prisma.NestFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestFindUniqueArgs>
  ): Promise<Nest | null> {
    return this.prisma.nest.findUnique(args);
  }
  async create<T extends Prisma.NestCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestCreateArgs>
  ): Promise<Nest> {
    return this.prisma.nest.create<T>(args);
  }
  async update<T extends Prisma.NestUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestUpdateArgs>
  ): Promise<Nest> {
    return this.prisma.nest.update<T>(args);
  }
  async delete<T extends Prisma.NestDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.NestDeleteArgs>
  ): Promise<Nest> {
    return this.prisma.nest.delete(args);
  }

  async findBills(
    parentId: string,
    args: Prisma.BillFindManyArgs
  ): Promise<Bill[]> {
    return this.prisma.nest
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .bills(args);
  }

  async findRents(
    parentId: string,
    args: Prisma.RentFindManyArgs
  ): Promise<Rent[]> {
    return this.prisma.nest
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .rents(args);
  }

  async findTenants(
    parentId: string,
    args: Prisma.TenantFindManyArgs
  ): Promise<Tenant[]> {
    return this.prisma.nest
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tenants(args);
  }

  async getPropertyId(parentId: string): Promise<Property | null> {
    return this.prisma.nest
      .findUnique({
        where: { id: parentId },
      })
      .propertyId();
  }
}
